package/liblo: add upstream patch to fix build error
Since the merge of gcc 13.x, a warning treated as error causes liblo
to fail building:

server.c: In function 'lo_server_del_lo_method':
server.c:2251:16: error: pointer 'prev' used after 'free' [-Werror=use-after-free]

Fixes:
http://autobuild.buildroot.net/results/c98/c98c21093714542d4c0546a742fdcc48f3f07d04/

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>