package/ipython: add missing dependencies
As reported [1], the test TestIPythonPy3 fail since it was updated
to 8.6.0 release just after 2022.11.

  ModuleNotFoundError: No module named 'stack_data'

Indeed there is no such python3-stack-data in Buildroot.
For example, Fedora packaging added python3-stack-data while updating
to ipython 8.0.1.

With python-stack-data added, the test TestIPythonPy3 still fail
with:

  ModuleNotFoundError: No module named 'sqlite3'

Since ipython 8 sqlite3 fallback imports has been removed [2].

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/4322819089

[1] http://lists.busybox.net/pipermail/buildroot/2023-May/668086.html
[2] https://github.com/ipython/ipython/commit/7a0bdabecfa745b60c3a711e1da2df378687e746

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>