package/libserial: fix gcc-13.x compile (add patch to add missing cstdint include)
Add patch taken from upstream pull request ([1]) to fix gcc-13.x compile
failure because of a missing csdtint include.

Fixes:

  In file included from libserial/SerialStreamBuf.h:36,
                   from SerialStreamBuf.cpp:34:
  ./libserial/SerialPortConstants.h:93:37: error: ‘uint8_t’ was not declared in this scope
     93 |     using DataBuffer =  std::vector<uint8_t> ;
        |                                     ^~~~~~~

[1] https://github.com/crayzeewulf/libserial/pull/186

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>