package/luvi: bump 2.14
lua-openssl (0.7.8-0) bundled in luvi 2.13 fail to build with openssl-3.x

test-output/TestLuvi/build/luvi-2.13.0/deps/lua-openssl/src/lbn.c:28:27: error: expected ')' before 'SHLIB_VERSION_NUMBER'
   28 |       "based on OpenSSL " SHLIB_VERSION_NUMBER
      |                           ^~~~~~~~~~~~~~~~~~~~

Luvi 2.14 include an lua-openssl update to 0.8.2-0 fixing TestLuvi.

See:
https://github.com/luvit/luvi/releases/tag/v2.14.0

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/4768561386

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>