package/assimp: needs gcc >= 7
Fixes:
http://autobuild.buildroot.net/results/d6c/d6caf3c2c0fd670e70950d3e89629df39f8ce596/

After adding various fixes for the autobuilder error and subsequent
build errors this build error can only be fixed by using gcc >= 7:

output/build/assimp-5.2.5/code/AssetLib/Obj/ObjFileParser.cpp:55:23:
 fatal error: string_view: No such file or directory

Usage of string_view was added in version 5.2.5 by upstream commit
https://github.com/assimp/assimp/commit/f6bcb160d08af267778fbc59b480ce5d9c52c92c
which was added to buildroot by commit
7d843d9cc0064d6690cfc000e579f575e2c0cc4d

Removed BR2_TOOLCHAIN_HAS_GCC_BUG_64735 which is only valid for gcc < 7

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>